// Coordinator-owned, narrowly approved PDF identity documents. Never scientific-source substitution.
import {readFileSync} from 'node:fs';
import {readFile as read,mkdir,lstat,realpath,readdir,mkdtemp,writeFile} from 'node:fs/promises';
import {createHash,randomUUID} from 'node:crypto';
import {dirname,join,relative,resolve,isAbsolute,sep} from 'node:path';
import {fileURLToPath} from 'node:url';
import {isDeepStrictEqual} from 'node:util';
import {runBounded} from './openscene-process.mjs';

export const IDENTITY_CONTRACT='wam-supporting-identity-documents-v1';
export const IDENTITY_PAPER='ref-47f59ffa32a9f466d486';
export const IDENTITY_DESCRIPTOR_SHA='9a80d8cba62cb08b05c6dfa6fd001085eebf430dee13a76c2467be865cfce6c1';
export const IDENTITY_APPROVAL={name:'probabilistic-robotics-root-supporting-identity-design-review-20260909T155815Z.json',sha256:'add4e934d2ac8d1cfd67cc9083bc3eaeb278229d6e24e85a65a3a7191ff52452'};
export const IDENTITY_SOURCE_SHA='5fb94e7c6a1cba964992f36ca8db1a5289ac40bddf8e28ad72e6b9917e29cfd6';
export const IDENTITY_TEXT_SHA='ad195f8892b5877a10ae87ec402b99003ee507f89762b4aa613b9de645ebc9d6';
const originalPins=[{"imageId":"page-10","kind":"source-page","page":10,"sha256":"09ece1493eb4be9abdd1e4c12221a91ad40f1679319f50310a7a0010dc3236e1"},{"imageId":"page-9","kind":"source-page","page":9,"sha256":"140c38d16940e1edbbdfcee1aada4b0b6428188b9f9d7dff854541a1653032c7"},{"imageId":"page-8","kind":"source-page","page":8,"sha256":"5eef3ea8dbafad3d9891d1d5993226499ca7f06ce0cf7047b8d95d5d7e731d53"},{"imageId":"page-7","kind":"source-page","page":7,"sha256":"82cbc537e13ec181a1d5bbf252a5bd7b6e8a11f90d8018b9fcfada1d6408b8a0"},{"imageId":"page-6","kind":"source-page","page":6,"sha256":"4e4cc0776b8937b45b9542df7760d6cab29ef33d9eca0ff3ed63243d0331522a"},{"imageId":"page-5","kind":"source-page","page":5,"sha256":"031990a2c169146a04f3780f7cecbef879ce9094729a1d6c45876b274c76bf7c"},{"imageId":"page-4","kind":"source-page","page":4,"sha256":"f84894b1f009f98fd9cc992e61064310fa1e7b7bd9b197c4cc9acec7b9e391fd"},{"imageId":"page-3","kind":"source-page","page":3,"sha256":"727b6a3d7f4494198e1038febdd8abc50c20762afa6afac952199f4d58b41a79"},{"imageId":"page-2","kind":"source-page","page":2,"sha256":"977f047aa02f4191bba4240c41a5250b3bd7e16f46d1badf8ca0f8f55bd847fd"},{"imageId":"page-1","kind":"source-page","page":1,"sha256":"938aa760c0a732843b525892c6a351c3715c6cae30154e6ec3a1ea143680653a"},{"imageId":"crop-markov-localization","kind":"crop","page":4,"sha256":"13ac2f000c65204f87377d1a1ae1d5ce05c55b6d9b5063f93a0b1ed6d52ddcc2"},{"imageId":"crop-coastal-navigation","kind":"crop","page":5,"sha256":"f70ae3580f3a3a37e51601b9442822d3cf80da2328501226fb215f94e354c566"}];
export const IDENTITY_DOCUMENT_IDS=['stanford-author','prh-publisher'];
export const IDENTITY_PAGE_ONE='Observed chapter heading 1 Introduction, PDF page1/printed3. This page does not contain book author, copyright, publication or edition credits. Those metadata claims are separately bound to supporting identity documents.';
export const IDENTITY_INSTRUCTIONS='SUPPORTING IDENTITY DOCUMENTS: This primary remains the ten-page PDF chapter; the two additional source-identity-document images are offline reflows of the separately retained original Stanford and PRH HTML. They are not PDF pages, covers, scientific figures, or full-book reading. Inspect both complete source text regions and source linkage; author/title/ISBN/date claims are localized by identitySupport.claimBindings. PDF page 1 has only the chapter heading and no author/publication credits. Nicholas Roy is a figure-image credit, not a book author. PRH Product Details were expanded from an initially closed drawer; 672 pages is product metadata, not reading scope. Historical affiliations are not current metadata. The sample printing remains unknown and MIT discovery is an acquisition attestation, not retained discovery DOM. Review every original PDF page, both original crops and both identity documents independently. Copy each reviewRole. All three flags must be truthful; unreadable or unsupported identity evidence fails identityMatches and approved. No hash, source-role or prior verdict supplies approval.';
export const identityHash=b=>createHash('sha256').update(b).digest('hex');
const hash=identityHash,need=(ok,m)=>{if(!ok)throw Error('Identity support: '+m);},same=(a,b,m)=>need(isDeepStrictEqual(a,b),m),valid=v=>typeof v==='string'&&/^[a-f0-9]{64}$/.test(v);
const own=new WeakMap();
export const identityCodeSha256=hash(readFileSync(fileURLToPath(import.meta.url)));
export const identityRendererPath=fileURLToPath(new URL('../reading/render-identity-support.mjs',import.meta.url));
export function identityCodeBinding(){need(hash(readFileSync(fileURLToPath(import.meta.url)))===identityCodeSha256,'module file changed after loading');return {moduleSha256:identityCodeSha256,rendererSha256:hash(readFileSync(identityRendererPath)),processSha256:hash(readFileSync(fileURLToPath(new URL('./openscene-process.mjs',import.meta.url))))};}
export async function identityFile(root,name,max=20_000_000){
 const base=await realpath(root),file=isAbsolute(name)?name:join(base,name),r=relative(base,file);need(r&&!isAbsolute(r)&&!r.split(sep).includes('..')&&resolve(file)===file,'unsafe input path');let cursor=base;
 for(const part of r.split(sep)){cursor=join(cursor,part);need(!(await lstat(cursor)).isSymbolicLink(),'symlink input');}
 const st=await lstat(file);need(st.isFile()&&st.nlink===1&&st.size<=max&&await realpath(file)===file,'unbounded, aliased or nonregular input');return file;
}
async function pinned(root,p,pins,max){need(p&&valid(p.sha256),'input without SHA');const path=await identityFile(root,p.path,max);const bytes=await read(path);need(hash(bytes)===p.sha256,'input fingerprint drift '+path);pins.set(path,{path,sha256:p.sha256});return bytes;}
function escape(s){return s.replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;').replaceAll("'",'&#x27;');}
const norm=s=>s.replace(/\s+/g,' ').trim();
// Deliberately not a general HTML sanitizer: only seven exact approved raw fragments.
export function deriveIdentityMarkup(raw,part){
 const [a,b]=part.rawUtf8ByteRange||[];need(Number.isSafeInteger(a)&&Number.isSafeInteger(b)&&a>=0&&b>a&&b<=raw.length,'raw range');const bytes=raw.subarray(a,b);need(hash(bytes)===part.rawSlice.sha256,'raw slice substitution');const s=new TextDecoder('utf-8',{fatal:true}).decode(bytes);
 const tokens=s.match(/<[^>]*>|[^<]+/g)||[];need(tokens.join('')===s,'malformed fragment');const out=[],texts=[],stack=[];
 for(const token of tokens){if(!token.startsWith('<')){need(!token.includes('&'),'unreviewed HTML entity in narrow profile');texts.push(token);out.push(escape(token));continue;}const m=token.match(/^<(\/)?([a-z][a-z0-9]*)(?:\s[^<>]*)?>$/i);need(m,'unrecognized original tag');const t=m[2].toLowerCase();need(['h1','h2','h3','div','p','span','a','blockquote','br','b','strong','em','i'].includes(t),'active or unsupported original tag');if(m[1]){need(stack.pop()===t,'unbalanced source markup');out.push('</'+t+'>');}else{if(t!=='br')stack.push(t);out.push('<'+t+'>');}}
 need(stack.length===0,'unclosed source fragment');const visible=norm(texts.join(' '));need(visible===part.visibleText&&hash(visible)===part.visibleTextSha256,'source text changed');return {markup:out.join(' '),visibleText:visible};
}
function selectorCheck(raw,part,doc){const s=raw.toString('utf8'),x=raw.subarray(...part.rawUtf8ByteRange).toString('utf8');
 const selectors={'book-title':/^<h1>Probabilistic Robotics<\/h1>$/,'author-heading':/^<h2>About the Authors<\/h2>$/,'author-biographies':/^<blockquote>/,'book-authors':/^<h2 class="contributors isbn-related 9780262201629 show">/,'product-heading':/^<span class="drawer-title">/,'product-details':/^<div class="drawer-copy-text no-bottom-margin">/};need(selectors[part.id]?.test(x),'selector mismatch');need(s.split(x).length===2,'selected original node is not unique');if(part.id.startsWith('product-'))need(s.slice(0,part.rawUtf8ByteRange[0]).includes('id="productdetails"'),'product node outside declared drawer');if(doc.id==='stanford-author'&&part.id==='author-biographies'){const h=doc.parts.find(p=>p.id==='author-heading');need(norm(raw.subarray(h.rawUtf8ByteRange[1],part.rawUtf8ByteRange[0]).toString())==='','author heading sibling mismatch');}}
export async function loadIdentityPack({workDir,descriptorPath,descriptorSha256=IDENTITY_DESCRIPTOR_SHA}){
 need(descriptorSha256===IDENTITY_DESCRIPTOR_SHA,'unapproved descriptor');const root=await realpath(workDir),path=await identityFile(root,descriptorPath,50_000),rel=relative(root,path);need(!rel.split(sep).includes('illustrated-runs'),'writer/run-owned identity input');const pins=new Map();const json=(await pinned(root,{path,sha256:descriptorSha256},pins,50_000)).toString('utf8'),d=JSON.parse(json);
 need(d.paperId===IDENTITY_PAPER&&d.primary.kind==='pdf'&&d.primary.source.sha256===IDENTITY_SOURCE_SHA&&d.primary.text.sha256===IDENTITY_TEXT_SHA&&d.primary.pageCount===10&&d.primary.unknownPrinting===true,'primary identity/scope mismatch');same(d.documents.map(x=>x.id),IDENTITY_DOCUMENT_IDS,'document inventory');
 await pinned(root,{path:join(root,'monitor-checkpoints',IDENTITY_APPROVAL.name),sha256:IDENTITY_APPROVAL.sha256},pins);
 for(const p of [d.primary.source,d.primary.text,d.primary.manifest,d.rootAuthorization,d.sampleLink.provenance,d.rendering.font,d.rendering.runtime.completePlaywrightInventory])await pinned(root,p,pins);
 const documents=[];for(const doc of d.documents){const raw=await pinned(root,doc.rawSource,pins),provenance=JSON.parse((await pinned(root,doc.acquisitionProvenance,pins)).toString());need(provenance.url===doc.canonicalUrl&&provenance.sha256===doc.rawSource.sha256,'source acquisition mismatch');const pieces=[];
  for(const p of doc.parts){selectorCheck(raw,p,doc);const v=deriveIdentityMarkup(raw,p);const exact=await pinned(root,p.rawSlice,pins);need(exact.equals(raw.subarray(...p.rawUtf8ByteRange)),'fragment file differs');pieces.push(v.markup);}
  const markup=pieces.join('\n');need(hash(markup)===doc.offlineMarkup.sha256,'fresh derivation differs from approved markup');need((await pinned(root,doc.offlineMarkup,pins)).equals(Buffer.from(markup)),'offline markup differs');documents.push({...doc,markup});}
 const rt=d.rendering.runtime,closure=JSON.parse((await read(rt.completePlaywrightInventory.path)).toString());need(Array.isArray(closure)&&closure.length>100,'incomplete Playwright closure');const runtimePins=[];
 for(const p of [...closure,{path:rt.nodePath,sha256:rt.nodeSha256},{path:rt.chromePath,sha256:rt.chromeSha256},{path:rt.playwrightPath,sha256:rt.playwrightEntrySha256}]){const file=await realpath(p.path),st=await lstat(file);need(st.isFile()&&st.size<600_000_000&&hash(await read(file))===p.sha256,'runtime fingerprint drift');runtimePins.push({path:file,sha256:p.sha256});}
 // Inventory closure is exhaustive for both installed packages, not only a supplied subset.
 const base=dirname(dirname(rt.playwrightPath)),found=[];for(const packageName of ['playwright','playwright-core']){async function walk(dir){for(const ent of await readdir(dir,{withFileTypes:true})){const p=join(dir,ent.name);need(!ent.isSymbolicLink(),'runtime symlink');if(ent.isDirectory())await walk(p);else if(ent.isFile())found.push(p);}}await walk(join(base,packageName));}
 same([...new Set(closure.map(p=>p.path))].sort(),found.sort(),'Playwright runtime closure missing/extra files');
 return {root,path,json,descriptorSha256,d,documents,inputFiles:[...pins.values()].sort((a,b)=>a.path.localeCompare(b.path)),runtimePins:[...new Map(runtimePins.map(x=>[x.path,x])).values()].sort((a,b)=>a.path.localeCompare(b.path)),code:identityCodeBinding()};
}
export async function loadIdentitySupportPlan({path,sha256,workDir,requested}){if(path===undefined&&sha256===undefined)return null;need(path&&sha256===IDENTITY_DESCRIPTOR_SHA&&requested.length===1&&requested[0]===IDENTITY_PAPER,'explicit single approved identity input required');const pack=await loadIdentityPack({workDir,descriptorPath:path,descriptorSha256:sha256});const token=Object.freeze({});own.set(token,pack);return token;}
export async function verifyIdentitySupportPlan(token,manifest){if(!token)return;const pack=own.get(token);need(pack,'plan is not coordinator-loaded');need(manifest.kind==='pdf'&&manifest.paperId===IDENTITY_PAPER&&manifest.sha256===IDENTITY_SOURCE_SHA&&manifest.textSha256===IDENTITY_TEXT_SHA&&manifest.pageCount===10,'different PDF source');const fresh=await loadIdentityPack({workDir:pack.root,descriptorPath:pack.path});same(fresh.code,pack.code,'identity code changed after plan load');same(fresh.inputFiles,pack.inputFiles,'identity inputs changed after plan load');same(fresh.runtimePins,pack.runtimePins,'identity runtime changed after plan load');}
export function identityRole(image){return image.kind==='source-identity-document'?'supporting-identity-document':image.kind==='source-page'?'supporting-source-page':image.kind==='crop'?'selected-final-crop':null;}
export function identityClaims(){return {chapterHeading:{value:'1 Introduction',imageIds:['page-1'],source:'scientific-primary-pdf'},bookTitle:{value:'Probabilistic Robotics',documentIds:IDENTITY_DOCUMENT_IDS},authors:{value:'Sebastian Thrun; Wolfram Burgard; Dieter Fox',documentIds:IDENTITY_DOCUMENT_IDS},isbn:{value:'9780262201629',documentIds:['prh-publisher']},publication:{publisher:'The MIT Press',date:'2005-08-19',documentIds:['prh-publisher']},printing:'unknown',scientificCoverage:'Chapter 1 Sections 1.1–1.6, ten PDF pages only'};}
export async function runIdentityRender(pack,directory){const result=await runBounded(pack.d.rendering.runtime.nodePath,[identityRendererPath,'--work-dir',pack.root,'--descriptor',pack.path,'--output',directory],{timeoutMs:120000,maxRssBytes:1_800_000_000,maxOutputBytes:2_000_000});const r=JSON.parse(result.stdout);validateIdentityRender(r,pack);need(r.pid===result.execution.pid,'renderer process identity mismatch');return {...r,processBudget:result.execution};}
export function validateIdentityRender(r,pack){need(r?.kind==='identity-original-text-render-v1'&&valid(r.jobId)&&Number.isInteger(r.pid)&&r.pid>0,'render identity');same(r.code,pack.code,'render code');same(r.inputFiles,pack.inputFiles,'render inputs');same(r.runtimePins,pack.runtimePins,'render runtime');same(r.descriptorSha256,pack.descriptorSha256,'render descriptor');same(r.outputs.map(x=>x.documentId),IDENTITY_DOCUMENT_IDS,'render output inventory');for(const o of r.outputs){need(valid(o.sha256)&&valid(o.wrapperSha256)&&o.width===1360&&o.height>=900&&o.height<4000&&o.networkRequests===0&&o.sourceScriptExecuted===false&&o.fontLoaded===true,'invalid render observations');same(o.rawSourceSha256,pack.d.documents.find(d=>d.id===o.documentId).rawSource.sha256,'render raw identity');}}
export async function appendIdentitySupport(packet,token){if(!token){need(!packet.identitySupport,'writer supplied identity contract');return packet;}const pack=own.get(token);need(pack,'identity plan must be coordinator-loaded');need(!packet.identitySupport&&!packet.sourceDetails&&!packet.context.config.htmlVisuals,'mixed or supplied identity contract');await verifyIdentitySupportPlan(token,packet.context.manifest);
 const original=packet.images.map(({path,...im})=>({...im,...(im.imageId==='page-1'?{description:IDENTITY_PAGE_ONE}:{}),reviewRole:identityRole(im)}));need(original.length===12&&original.filter(x=>x.kind==='source-page').length===10&&original.filter(x=>x.kind==='crop').length===2,'all scientific originals required');
 const root=join(pack.root,'monitor-checkpoints');const dir=await mkdtemp(join(root,'identity-render-'));const rendered=await runIdentityRender(pack,join(dir,'render'));const images=packet.images.map(im=>({...im,...(im.imageId==='page-1'?{description:IDENTITY_PAGE_ONE}:{}),reviewRole:identityRole(im)}));for(const o of rendered.outputs)images.push({imageId:'identity-'+o.documentId,path:o.path,sha256:o.sha256,kind:'source-identity-document',reviewRole:'supporting-identity-document',description:{documentId:o.documentId,canonicalUrl:pack.d.documents.find(d=>d.id===o.documentId).canonicalUrl,rawSourceSha256:o.rawSourceSha256,scope:'Book identity only; unchanged chapter PDF remains sole scientific source.',derivation:pack.d.documents.find(d=>d.id===o.documentId).derivation}});
 const identitySupport={version:IDENTITY_CONTRACT,descriptorPath:pack.path,descriptorSha256:pack.descriptorSha256,planJson:pack.json,rootApprovalSha256:IDENTITY_APPROVAL.sha256,sourceTextSha256:IDENTITY_TEXT_SHA,claimBindings:identityClaims(),originalScientificImages:original,render:rendered};const result={...packet,images,identitySupport};validateIdentitySupportContext({sourceKind:'pdf',paperId:packet.context.paper.id,sourceSha256:packet.context.manifest.sha256,metadata:packet.metadata,report:packet.report,edition:packet.edition,images:images.map(({path,...x})=>x),identitySupport});return result;
}
export function validateIdentitySupportContext(c){const images=c?.images||[],has=images.some(i=>i.kind==='source-identity-document'||i.reviewRole==='supporting-identity-document');if(!c?.identitySupport){need(!has,'identity image without typed contract');return [];}
 const p=c.identitySupport;need(Object.keys(p).length===9&&['version','descriptorPath','descriptorSha256','planJson','rootApprovalSha256','sourceTextSha256','claimBindings','originalScientificImages','render'].every(k=>Object.hasOwn(p,k)),'unknown identity contract fields');need(p.version===IDENTITY_CONTRACT&&c.sourceKind==='pdf'&&!c.sourceDetails&&!c.htmlRendering&&c.paperId===IDENTITY_PAPER&&c.sourceSha256===IDENTITY_SOURCE_SHA&&p.sourceTextSha256===IDENTITY_TEXT_SHA&&p.descriptorSha256===IDENTITY_DESCRIPTOR_SHA&&hash(p.planJson)===IDENTITY_DESCRIPTOR_SHA&&p.rootApprovalSha256===IDENTITY_APPROVAL.sha256,'identity source/contract mismatch');const d=JSON.parse(p.planJson);same(d.documents.map(x=>x.id),IDENTITY_DOCUMENT_IDS,'identity documents');same(p.claimBindings,identityClaims(),'metadata claim localization');need(Object.keys(c.metadata).length===4&&['title','sourceSha256','page','authors'].every(k=>Object.hasOwn(c.metadata,k))&&c.metadata.sourceSha256===IDENTITY_SOURCE_SHA,'unknown metadata claim');need(c.metadata.title==='1 Introduction'&&c.metadata.page===1&&c.metadata.authors===identityClaims().authors.value&&!c.metadata.affiliations,'metadata unsupported or mislocated');need(c.report.coverage.scope==='selected-sections'&&c.report.coverage.identityVerified===true,'chapter identity/scope still unresolved');same([...c.edition.visualAudit.inspectedPages].sort((a,b)=>a-b),[1,2,3,4,5,6,7,8,9,10],'declared scientific page scope changed');need(c.report.sources.length===1&&c.report.sources[0].sha256===IDENTITY_SOURCE_SHA&&c.edition.visuals.length===2,'identity expanded scientific scope');need(images.length===14&&new Set(images.map(i=>i.imageId)).size===14,'identity inventory must be exactly fourteen');
 const originals=p.originalScientificImages;const select=x=>({imageId:x.imageId,kind:x.kind,page:x.page,sha256:x.sha256});same(originals.map(select).sort((a,b)=>a.imageId.localeCompare(b.imageId)),originalPins.map(select).sort((a,b)=>a.imageId.localeCompare(b.imageId)),'original pinned science inventory drift');need(originals.length===12&&new Set(originals.map(x=>x.imageId)).size===12,'original inventory');same(originals.filter(x=>x.kind==='source-page').map(x=>x.page).sort((a,b)=>a-b),[1,2,3,4,5,6,7,8,9,10],'all ten original pages');need(originals.filter(x=>x.kind==='crop').length===2,'both original crops');for(const old of originals){const expected={...old,...(old.imageId==='page-1'?{description:IDENTITY_PAGE_ONE}:{})};same(images.find(x=>x.imageId===old.imageId),expected,'original scientific image/description changed');}
 const r=p.render;const budget=r.processBudget;need(budget&&budget.pid===r.pid&&budget.exitCode===0&&budget.ownedTreeExitConfirmed===true&&budget.processGroupOwned===true&&budget.rssSamples>0&&budget.peakRssBytes<=budget.rssLimitBytes,'accepted renderer did not complete under guard');validateIdentityRender(r,{code:identityCodeBinding(),inputFiles:r.inputFiles,runtimePins:r.runtimePins,descriptorSha256:IDENTITY_DESCRIPTOR_SHA,d});const extra=images.filter(x=>x.kind==='source-identity-document');same(extra.map(x=>x.imageId),IDENTITY_DOCUMENT_IDS.map(x=>'identity-'+x),'identity attachment IDs');for(const x of extra){const doc=d.documents.find(doc=>'identity-'+doc.id===x.imageId),o=r.outputs.find(o=>o.documentId===doc.id);need(!Object.hasOwn(x,'page')&&x.reviewRole==='supporting-identity-document'&&x.sha256===o.sha256,'identity attachment pair/page');same(x.description,{documentId:doc.id,canonicalUrl:doc.canonicalUrl,rawSourceSha256:doc.rawSource.sha256,scope:'Book identity only; unchanged chapter PDF remains sole scientific source.',derivation:doc.derivation},'identity description');}return extra;
}
