#!/usr/bin/env node
import { fileURLToPath } from 'node:url';
import { CATEGORIES, atomicWriteFiles, coverage, readJson, sortPapers, validateMeta, validatePapers } from './lib/data.mjs';

const ROOT = new URL('../', import.meta.url);
const website = 'https://beat-in-our-hearts.github.io/Awesome-World-Action-Model/';
const repository = 'https://github.com/Beat-in-our-hearts/Awesome-World-Action-Model';
const escape = (value) => String(value).replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/\|/g, '&#124;').replace(/\[/g, '&#91;').replace(/\]/g, '&#93;').replace(/[\r\n]+/g, ' ');
const link = (label, url) => `[${escape(label)}](<${url.replace(/>/g, '%3E').replace(/</g, '%3C')}>)`;
const anchor = (category) => `category-${CATEGORIES.indexOf(category) + 1}`;

try {
  const papers = sortPapers(validatePapers(await readJson(fileURLToPath(new URL('data/papers.json', ROOT)))));
  const meta = validateMeta(await readJson(fileURLToPath(new URL('data/meta.json', ROOT))), papers);
  const stats = coverage(papers);
  const lines = [
    '<!-- Generated by scripts/generate-readme.mjs. Update the source data or generator, then regenerate. -->',
    '# Awesome World Action Model', '',
    'A curated, searchable collection of research on world action models: learning to understand, predict, and act in the physical world.', '',
    `**[Explore the website](${website})** · [Browse the data](data/papers.json) · [Suggest a paper](${repository}/issues/new?template=paper.yml)`, '',
    `**${stats.papers} papers · ${CATEGORIES.length} research categories · ${stats.code} with code · ${stats.project} with project pages**`, '',
    `Current collection: **${meta.sourceDateRange.start} – ${meta.sourceDateRange.end}** (arXiv submission dates). Last imported: **${meta.updatedAt.slice(0, 10)}**.`, '',
    'The website provides text search, category and date filters, and paper pages containing the full author list, affiliations, contribution, and abstract. Missing code, project, or venue links mean that these fields have not yet been recorded; they are not a claim that none exist.', '',
    '## Research categories', '',
    '| Category | Papers |', '| --- | ---: |',
    ...CATEGORIES.map((category) => `| [${escape(category)}](#${anchor(category)}) | ${papers.filter((paper) => paper.primaryCategory === category).length} |`), '',
  ];
  for (const category of CATEGORIES) {
    lines.push(`<a id="${anchor(category)}"></a>`, `## ${category}`, '', '| Date | Paper | Links | Secondary categories |', '| --- | --- | --- | --- |');
    for (const paper of papers.filter((entry) => entry.primaryCategory === category)) {
      const links = [link('arXiv', paper.arxivUrl), ...paper.codeUrls.map((url, index) => link(paper.codeUrls.length > 1 ? `Code ${index + 1}` : 'Code', url))];
      if (paper.projectUrl) links.push(link('Project', paper.projectUrl));
      if (paper.venue) links.push(escape(paper.venue));
      lines.push(`| ${paper.submittedDate} | ${escape(paper.title)} | ${links.join(' · ')} | ${paper.secondaryCategories.map(escape).join('; ') || '—'} |`);
    }
    lines.push('');
  }
  lines.push(
    '## Contributing', '',
    `[Open a paper suggestion](${repository}/issues/new?template=paper.yml) with an arXiv URL, a short explanation of relevance, and any official code or project links. Corrections and website improvements are welcome through issues and pull requests. Maintainers review suggestions and update the Notion source before exporting a new catalog.`, '',
    '## Local development', '',
    'Use the Node.js version specified in the repository, then:', '',
    '```sh', 'npm ci', 'npm run dev', '```', '',
    'Before opening a pull request:', '', '```sh', 'npm run validate:data', 'npm test', 'npm run build', '```', '',
    '## Updating the paper catalog', '',
    'Notion is the editorial source. The public, versioned catalog in `data/papers.json` is shared by the website and this README. Builds use the committed catalog and need no Notion credentials.', '',
    'Configure `NOTION_API_TOKEN` with a read-only Notion integration and `NOTION_DATA_SOURCE_ID` with the intended data source ID in your local environment or GitHub Actions configuration. Neither value belongs in the repository. Give the integration access to the source database.', '',
    '```sh', '# Preview a complete, validated export without changing files', 'npm run sync:notion -- --check', '', '# Update the catalog, regenerate this README, and validate', 'npm run sync:notion', 'npm run generate:readme', 'npm run validate:data', '```', '',
    'To use a locally authenticated Notion CLI, run `npm run sync:notion -- --cli` with `NOTION_DATA_SOURCE_ID` configured. An offline audit snapshot can be imported with `npm run sync:notion -- --input /path/to/private-snapshot.json`. Raw snapshots include private Notion metadata and must remain outside this repository.', '',
    'The exporter reads every result page, retries transient failures, preserves all rich-text fragments, and publishes only the 14 explicit paper fields. It validates unique arXiv IDs, canonical URLs, calendar dates, categories, and safe HTTP(S) links before replacing the generated files. An empty result or a decrease of more than 20% is rejected. After checking the source, maintainers can intentionally override these guards with `--allow-empty` and/or `--allow-large-decrease`; normal website validation still requires a nonempty catalog.', '',
    'The source fields map as follows:', '',
    '| Notion field | Public field |', '| --- | --- |',
    '| Paper Name | `title` |', '| Paper URL | `id`, `arxivUrl` |', '| Authors | `authors` |', '| Author Affiliations | `affiliations` |',
    '| Contribution | `contribution` |', '| English Abstract | `abstract` |', '| Submitted Date | `submittedDate` |',
    '| Primary Category | `primaryCategory` |', '| Secondary Categories | `secondaryCategories` (`None` becomes an empty list) |',
    '| BibTeX Key | `bibtexKey` |', '| Code URL | `codeUrls` |', '| Web Page | `projectUrl` |', '| 论文收录 | `venue` |', '',
    'See [deployment and synchronization setup](docs/MAINTAINING.md) for GitHub Pages and automated update configuration.', '',
    '## License', '',
    'Repository code is provided under the [MIT License](LICENSE). Paper abstracts and other attributed research content remain the work of their respective authors and rights holders.', '',
  );
  await atomicWriteFiles([[fileURLToPath(new URL('README.md', ROOT)), `${lines.join('\n')}\n`]]);
  console.log(`Generated README.md from ${papers.length} papers.`);
} catch (error) { console.error(`README generation failed: ${error.message}`); process.exitCode = 1; }
