#!/usr/bin/env node
import { fileURLToPath, pathToFileURL } from 'node:url';
import { CATEGORIES, atomicWriteFiles, coverage, readJson, sortPapers, validateMeta, validatePapers } from './lib/data.mjs';
import { MAJOR_CATEGORIES, QUADRANTS, QUADRANT_STATUSES, taxonomyLabel } from '../src/lib/taxonomy.mjs';
import { venueLabel } from '../src/lib/display.mjs';

const ROOT = new URL('../', import.meta.url);
const repositoryName = 'RCL-Robotics/Awesome-World-Action-Model';
const repository = `https://github.com/${repositoryName}`;
const website = 'https://rcl-robotics.github.io/Awesome-World-Action-Model/';
const generatedNotice = '<!-- Generated by scripts/generate-readme.mjs. Update the source data or generator, then regenerate. -->';
const escape = (value) => String(value).replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/\|/g, '&#124;').replace(/\[/g, '&#91;').replace(/\]/g, '&#93;').replace(/[\r\n]+/g, ' ');
const link = (label, url) => `[${escape(label)}](<${url.replace(/>/g, '%3E').replace(/</g, '%3C')}>)`;
const majorAnchor = (category) => category === null ? 'major-not-recorded' : `major-${taxonomyLabel(category).toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '')}`;
const majorLabel = (category) => category === null ? 'Major category not recorded' : taxonomyLabel(category);
const browse = (key, value) => `${website}?${key}=${encodeURIComponent(value ?? '__unassigned__')}#library`;
const quadrantLabel = (quadrant) => {
  const index = QUADRANTS.indexOf(quadrant);
  return index >= 0 ? `Q${index + 1}` : quadrant === null ? 'Quadrant not recorded' : taxonomyLabel(quadrant);
};
const categoryDescriptions = {
  'Foundational work': 'World models, model-based RL, planning, theory, and surveys',
  VLA: 'Vision-language-action policies and their learning methods',
  WAM: 'Models connecting world prediction with action generation and control',
  Datasets: 'Robot demonstrations, interaction data, video, and multimodal resources',
  'Evaluation metrics': 'Prediction quality, action consistency, and control performance',
  'Benchmarks & simulators': 'Evaluation tasks, environments, and simulation platforms',
  'WAM Components': 'Encoders, predictive backbones, action interfaces, and training methods',
};

function catalog(inputPapers, inputMeta) {
  const papers = sortPapers(validatePapers(inputPapers));
  const meta = validateMeta(inputMeta, papers);
  const majorGroups = [...MAJOR_CATEGORIES, ...(papers.some(paper => paper.majorCategory === null) ? [null] : [])];
  return { papers, meta, majorGroups, stats: coverage(papers) };
}

export function renderReadme(inputPapers, inputMeta) {
  const { papers, meta, majorGroups, stats } = catalog(inputPapers, inputMeta);
  const quadrantLink = (index) => `${link(`Q${index + 1}`, browse('quadrant', QUADRANTS[index]))} · ${papers.filter(paper => paper.quadrant === QUADRANTS[index]).length} entries`;
  const starChart = `https://api.star-history.com/chart?repos=${repositoryName}&amp;type=date&amp;legend=top-left`;
  return [
    generatedNotice,
    '<div align="center">',
    '  <h1>Awesome World Action Model</h1>',
    '  <p>',
    `    <a href="${website}"><img src="https://img.shields.io/badge/Web-Project_Page-2F6FEB?style=for-the-badge&amp;logo=googlechrome&amp;logoColor=white" alt="Web: Project Page" /></a>`,
    '    <img src="https://img.shields.io/badge/arXiv-Coming_Soon-B31B1B?style=for-the-badge&amp;logo=arxiv&amp;logoColor=white" alt="arXiv: Coming Soon" />',
    '  </p>',
    '  <p><strong>World-Action Models for Robot Learning and Control: A Survey</strong></p>',
    '  <p>',
    '    Zuxing&nbsp;Lu<sup>1,*</sup>, Hongjia&nbsp;Zhai<sup>1,*</sup>, Guanzhi&nbsp;Wang<sup>2</sup>, Huajian&nbsp;Zeng<sup>1</sup>,<br />',
    '    Jiaqi&nbsp;Yang<sup>1</sup>, Jingyu&nbsp;Liu<sup>1</sup>, Lei&nbsp;Cheng<sup>1</sup>, Yuantai&nbsp;Zhang<sup>1</sup>,<br />',
    '    Yuheng&nbsp;Qiu<sup>3</sup>, Zezhou&nbsp;Cheng<sup>4</sup>, Ivan&nbsp;Laptev<sup>1</sup>, Danfei&nbsp;Xu<sup>5</sup>,<br />',
    '    Benjamin&nbsp;Riviere<sup>6</sup>, Giuseppe&nbsp;Loianno<sup>7</sup>, Eric&nbsp;Xing<sup>1</sup>, Xingxing&nbsp;Zuo<sup>1,†</sup>',
    '  </p>',
    '  <p>',
    '    <sup>1</sup> MBZUAI &nbsp;·&nbsp; <sup>2</sup> Caltech &nbsp;·&nbsp; <sup>3</sup> Amazon FAR<br />',
    '    <sup>4</sup> University of Virginia &nbsp;·&nbsp; <sup>5</sup> Georgia Tech<br />',
    '    <sup>6</sup> New York University &nbsp;·&nbsp; <sup>7</sup> UC Berkeley',
    '  </p>',
    '  <p><sup>*</sup> Equal contribution &nbsp;·&nbsp; <sup>†</sup> Corresponding author</p>',
    '</div>', '',
    '## Our view of WAM', '',
    '> **A World-Action Model (WAM) connects future-state modeling with executable action generation to support predictive robot control.**', '',
    'Given observation history and a task instruction, a WAM models both what may happen next and which actions can bring about that future. The connection can be learned through joint world-action prediction or through a plan-then-act process that translates predicted futures into actions using inverse dynamics.', '',
    '| Model family | Central role |',
    '| --- | --- |',
    '| World Model (WM) | Predict how the environment evolves, often conditioned on actions. |',
    '| Vision-Language-Action model (VLA) | Map visual observations and language instructions to actions. |',
    '| World-Action Model (WAM) | Couple future-state prediction with action generation for planning and control. |', '',
    'Our focus is on **whether predicted futures are useful for action**: how predictions ground executable behavior, support look-ahead decisions, and remain consistent with the physical consequences of control. We examine this connection across representations, model components, architecture, training, data, and evaluation.', '',
    'The collection covers complete WAM systems alongside related foundations, VLA policies, reusable components, datasets, and evaluation resources.', '',
    '## Navigation', '',
    '- [Browse by major category](#major-categories)',
    '- [Compare the four architecture families](#architecture-index)',
    '- [Find repository resources](#repository-guide)',
    '- [Citation](#citation)',
    '- [Star history](#star-history)', '',
    `[Project website](${website}) · [Full paper catalog](docs/PAPERS.md) · [Reading reports](${website}reports/)`, '',
    `**${stats.papers} entries · ${MAJOR_CATEGORIES.length} major categories** · Catalog updated ${meta.updatedAt.slice(0, 10)}`, '',
    '## Major categories', '',
    'Click a category to jump to its paper list in this repository. Use **Browse** to search and filter the same category on the website.', '',
    '| Category | What you will find | Entries | Interactive view |',
    '| --- | --- | ---: | --- |',
    ...majorGroups.map(category => `| [${escape(majorLabel(category))}](docs/PAPERS.md#${majorAnchor(category)}) | ${categoryDescriptions[majorLabel(category)] ?? 'Entries awaiting a recorded major category'} | ${papers.filter(paper => paper.majorCategory === category).length} | ${link('Browse', browse('major', category))} |`), '',
    '## Architecture index', '',
    'We compare two design choices: **One Model or Dual-system** architecture, and **joint prediction or inverse dynamics (IDM)** for connecting worlds and actions. Click a quadrant to browse its entries.', '',
    '| Architecture | Joint prediction | Inverse dynamics (IDM) |',
    '| --- | --- | --- |',
    `| One Model | ${quadrantLink(0)} | ${quadrantLink(1)} |`,
    `| Dual-system | ${quadrantLink(2)} | ${quadrantLink(3)} |`, '',
    'Joint training alone does not establish a One Model architecture. [Other classification states](docs/PAPERS.md#classification-summary) retain entries outside the four quadrants, entries for which the taxonomy does not apply, and cases awaiting verification.', '',
    '## Repository guide', '',
    '| Resource | Where to go |',
    '| --- | --- |',
    '| Complete paper lists and source links | [Paper catalog](docs/PAPERS.md) |',
    '| Thematic browsing | [Research topics](docs/PAPERS.md#research-topics) |',
    `| Visual category and architecture maps | [Research map](${website}map/) |`,
    `| Detailed paper analyses | [Reading reports](${website}reports/) |`,
    '| Machine-readable bibliography | [papers.json](data/papers.json) |',
    '| Setup, catalog updates, and contribution workflow | [Maintainer guide](docs/MAINTAINING.md) |',
    `| Recommend a paper or report a correction | [Open an issue](${repository}/issues/new/choose) |`,
    '| Repository code license | [MIT License](LICENSE) |', '',
    'Paper abstracts and other attributed research content remain the work of their respective authors and rights holders.', '',
    '## Citation', '',
    '<!-- Citation placeholder: add the verified paper reference and BibTeX here when available. -->',
    '*Citation details and BibTeX will be added here when available.*', '',
    '## Star History', '',
    'The chart tracks this repository\'s GitHub stars over time and fills in as stars are recorded.', '',
    `<a href="https://www.star-history.com/?repos=${encodeURIComponent(repositoryName)}&amp;type=date&amp;legend=top-left">`,
    '  <picture>',
    `    <source media="(prefers-color-scheme: dark)" srcset="${starChart}&amp;theme=dark" />`,
    `    <source media="(prefers-color-scheme: light)" srcset="${starChart}" />`,
    `    <img alt="Star history of RCL-Robotics/Awesome-World-Action-Model" src="${starChart}" width="800" />`,
    '  </picture>',
    '</a>', '',
  ].join('\n');
}

export function renderPaperCatalog(inputPapers, inputMeta) {
  const { papers, meta, majorGroups, stats } = catalog(inputPapers, inputMeta);
  const lines = [
    generatedNotice, '# Paper catalog', '',
    `[← Repository overview](../README.md) · [Search the collection](${website}#library) · [Reading reports](${website}reports/)`, '',
    `**${stats.papers} entries** · Catalog updated ${meta.updatedAt.slice(0, 10)}`, '',
    'Each entry appears once below, under its recorded major category. Subcategories and quadrants describe different aspects of a contribution. Original research topics are retained as a separate thematic index.', '',
    '## Category index', '',
    '| Category | Entries |', '| --- | ---: |',
    ...majorGroups.map(category => `| [${escape(majorLabel(category))}](#${majorAnchor(category)}) | ${papers.filter(paper => paper.majorCategory === category).length} |`), '',
    '[Classification summary](#classification-summary) · [Research topics](#research-topics)', '',
  ];
  for (const category of majorGroups) {
    lines.push(`<a id="${majorAnchor(category)}"></a>`, '', `## ${majorLabel(category)}`, '', '[↑ Category index](#category-index)', '', '| Date / year | Paper or reference | Links | Subcategories · quadrant |', '| --- | --- | --- | --- |');
    for (const paper of papers.filter(entry => entry.majorCategory === category)) {
      const links = [link(paper.arxivUrl ? 'arXiv' : 'Paper', paper.paperUrl), ...paper.codeUrls.map((url, index) => link(paper.codeUrls.length > 1 ? `Code ${index + 1}` : 'Code', url))];
      if (paper.pdfUrl && paper.pdfUrl !== paper.paperUrl) links.push(link('PDF', paper.pdfUrl));
      if (paper.doi && paper.doi !== paper.paperUrl) links.push(link('DOI', paper.doi));
      if (paper.projectUrl) links.push(link('Project', paper.projectUrl));
      if (paper.venue) links.push(escape(venueLabel(paper.venue)));
      const classification = [...paper.subcategories.map(name => escape(taxonomyLabel(name))), escape(quadrantLabel(paper.quadrant))];
      lines.push(`| ${paper.submittedDate ?? paper.publicationYear ?? '—'} | ${escape(paper.title)} | ${links.join(' · ')} | ${classification.join(' · ')} |`);
    }
    lines.push('');
  }
  lines.push(
    '## Classification summary', '',
    'Quadrants cross architecture and prediction paradigm. The remaining states stay separate; missing classifications are not inferred.', '',
    '| Quadrant or state | Entries |', '| --- | ---: |',
    ...[...QUADRANT_STATUSES, ...(papers.some(paper => paper.quadrant === null) ? [null] : [])].map(quadrant => `| ${link(quadrant === null ? 'Not recorded' : taxonomyLabel(quadrant), browse('quadrant', quadrant))} | ${papers.filter(paper => paper.quadrant === quadrant).length} |`), '',
    '## Research topics', '',
    'These links filter the original Primary Category field. A missing original topic does not imply that the major category or quadrant is missing.', '',
    '| Research topic | Entries |', '| --- | ---: |',
    ...[...CATEGORIES, 'Uncategorized'].map(category => `| ${link(category === 'Uncategorized' ? 'Original topic not recorded' : category, browse('category', category))} | ${papers.filter(paper => paper.primaryCategory === category).length} |`), '',
    '[← Repository overview](../README.md) · [↑ Category index](#category-index)', '',
  );
  return lines.join('\n');
}

if (process.argv[1] && import.meta.url === pathToFileURL(process.argv[1]).href) {
  try {
    const papers = await readJson(fileURLToPath(new URL('data/papers.json', ROOT)));
    const meta = await readJson(fileURLToPath(new URL('data/meta.json', ROOT)));
    await atomicWriteFiles([
      [fileURLToPath(new URL('README.md', ROOT)), renderReadme(papers, meta)],
      [fileURLToPath(new URL('docs/PAPERS.md', ROOT)), renderPaperCatalog(papers, meta)],
    ]);
    console.log(`Generated README.md and docs/PAPERS.md from ${papers.length} papers.`);
  } catch (error) { console.error(`README generation failed: ${error.message}`); process.exitCode = 1; }
}
